name: Schedule dbt

on:
  push:  # 1. run when new code is pushed
  schedule: # 2. also run once every day at 8am
   - cron:  '0 8 * * *'

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - name: checkout # 3. check out models
      - uses: actions/checkout@v2 

      - name: dbt-run # 4. run dbt
        id: dbt-run
        uses: mwhitaker/dbt-action@master  
        with:
          dbt_command: "dbt run --profiles-dir ." # the actual dbt command!
          dbt_project_folder: "dbt-learn"
      - name: Get the result
        if: ${{ always() }}
        run: echo "${{ steps.dbt-run.outputs.result }}"
        shell: bash
      - name: SendGrid # 5. send email
        uses: peter-evans/sendgrid-action@v1 
        env:
          SENDGRID_API_KEY: $ # credentials to access this service
          SENDGRID_FROM: $
          SENDGRID_TO: $
